project_id = "eivajusgigmpatpmsynw"

[functions.stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-connect-create]
verify_jwt = true

[functions.stripe-connect-refresh]
verify_jwt = true
