/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as MeusPedidosRouteImport } from './routes/meus-pedidos'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as BeneficiosRouteImport } from './routes/beneficios'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as PedidoSucessoIdRouteImport } from './routes/pedido-sucesso.$id'
import { Route as AuthenticatedUnitsRouteImport } from './routes/_authenticated/units'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedPromotionsRouteImport } from './routes/_authenticated/promotions'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedMenuRouteImport } from './routes/_authenticated/menu'
import { Route as AuthenticatedLoyaltyRouteImport } from './routes/_authenticated/loyalty'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedFinanceAiRouteImport } from './routes/_authenticated/finance-ai'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedConsultorRouteImport } from './routes/_authenticated/consultor'
import { Route as AuthenticatedBuildersRouteImport } from './routes/_authenticated/builders'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as RSlugIndexRouteImport } from './routes/r.$slug.index'
import { Route as RSlugSobreRouteImport } from './routes/r.$slug.sobre'
import { Route as RSlugMontarRouteImport } from './routes/r.$slug.montar'

const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusPedidosRoute = MeusPedidosRouteImport.update({
  id: '/meus-pedidos',
  path: '/meus-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiosRoute = BeneficiosRouteImport.update({
  id: '/beneficios',
  path: '/beneficios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoSucessoIdRoute = PedidoSucessoIdRouteImport.update({
  id: '/pedido-sucesso/$id',
  path: '/pedido-sucesso/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUnitsRoute = AuthenticatedUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromotionsRoute = AuthenticatedPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenuRoute = AuthenticatedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLoyaltyRoute = AuthenticatedLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceAiRoute = AuthenticatedFinanceAiRouteImport.update({
  id: '/finance-ai',
  path: '/finance-ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsultorRoute = AuthenticatedConsultorRouteImport.update({
  id: '/consultor',
  path: '/consultor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuildersRoute = AuthenticatedBuildersRouteImport.update({
  id: '/builders',
  path: '/builders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const RSlugIndexRoute = RSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RSlugRoute,
} as any)
const RSlugSobreRoute = RSlugSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => RSlugRoute,
} as any)
const RSlugMontarRoute = RSlugMontarRouteImport.update({
  id: '/montar',
  path: '/montar',
  getParentRoute: () => RSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/beneficios': typeof BeneficiosRoute
  '/cliente': typeof ClienteRoute
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/favoritos': typeof FavoritosRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai': typeof AuthenticatedAiRoute
  '/builders': typeof AuthenticatedBuildersRoute
  '/consultor': typeof AuthenticatedConsultorRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/finance-ai': typeof AuthenticatedFinanceAiRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/loyalty': typeof AuthenticatedLoyaltyRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/pedido-sucesso/$id': typeof PedidoSucessoIdRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/r/$slug/montar': typeof RSlugMontarRoute
  '/r/$slug/sobre': typeof RSlugSobreRoute
  '/r/$slug/': typeof RSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/beneficios': typeof BeneficiosRoute
  '/cliente': typeof ClienteRoute
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/favoritos': typeof FavoritosRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai': typeof AuthenticatedAiRoute
  '/builders': typeof AuthenticatedBuildersRoute
  '/consultor': typeof AuthenticatedConsultorRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/finance-ai': typeof AuthenticatedFinanceAiRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/loyalty': typeof AuthenticatedLoyaltyRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/pedido-sucesso/$id': typeof PedidoSucessoIdRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/r/$slug/montar': typeof RSlugMontarRoute
  '/r/$slug/sobre': typeof RSlugSobreRoute
  '/r/$slug': typeof RSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/beneficios': typeof BeneficiosRoute
  '/cliente': typeof ClienteRoute
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/favoritos': typeof FavoritosRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/builders': typeof AuthenticatedBuildersRoute
  '/_authenticated/consultor': typeof AuthenticatedConsultorRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/finance-ai': typeof AuthenticatedFinanceAiRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/loyalty': typeof AuthenticatedLoyaltyRoute
  '/_authenticated/menu': typeof AuthenticatedMenuRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/promotions': typeof AuthenticatedPromotionsRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/units': typeof AuthenticatedUnitsRoute
  '/pedido-sucesso/$id': typeof PedidoSucessoIdRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/r/$slug/montar': typeof RSlugMontarRoute
  '/r/$slug/sobre': typeof RSlugSobreRoute
  '/r/$slug/': typeof RSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/beneficios'
    | '/cliente'
    | '/entrar'
    | '/esqueci-senha'
    | '/favoritos'
    | '/meus-pedidos'
    | '/redefinir-senha'
    | '/admin'
    | '/ai'
    | '/builders'
    | '/consultor'
    | '/customers'
    | '/dashboard'
    | '/finance'
    | '/finance-ai'
    | '/inventory'
    | '/loyalty'
    | '/menu'
    | '/orders'
    | '/promotions'
    | '/reviews'
    | '/settings'
    | '/suppliers'
    | '/units'
    | '/pedido-sucesso/$id'
    | '/pedido/$id'
    | '/r/$slug'
    | '/r/$slug/montar'
    | '/r/$slug/sobre'
    | '/r/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/beneficios'
    | '/cliente'
    | '/entrar'
    | '/esqueci-senha'
    | '/favoritos'
    | '/meus-pedidos'
    | '/redefinir-senha'
    | '/admin'
    | '/ai'
    | '/builders'
    | '/consultor'
    | '/customers'
    | '/dashboard'
    | '/finance'
    | '/finance-ai'
    | '/inventory'
    | '/loyalty'
    | '/menu'
    | '/orders'
    | '/promotions'
    | '/reviews'
    | '/settings'
    | '/suppliers'
    | '/units'
    | '/pedido-sucesso/$id'
    | '/pedido/$id'
    | '/r/$slug/montar'
    | '/r/$slug/sobre'
    | '/r/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/beneficios'
    | '/cliente'
    | '/entrar'
    | '/esqueci-senha'
    | '/favoritos'
    | '/meus-pedidos'
    | '/redefinir-senha'
    | '/_authenticated/admin'
    | '/_authenticated/ai'
    | '/_authenticated/builders'
    | '/_authenticated/consultor'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/finance'
    | '/_authenticated/finance-ai'
    | '/_authenticated/inventory'
    | '/_authenticated/loyalty'
    | '/_authenticated/menu'
    | '/_authenticated/orders'
    | '/_authenticated/promotions'
    | '/_authenticated/reviews'
    | '/_authenticated/settings'
    | '/_authenticated/suppliers'
    | '/_authenticated/units'
    | '/pedido-sucesso/$id'
    | '/pedido/$id'
    | '/r/$slug'
    | '/r/$slug/montar'
    | '/r/$slug/sobre'
    | '/r/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BeneficiosRoute: typeof BeneficiosRoute
  ClienteRoute: typeof ClienteRoute
  EntrarRoute: typeof EntrarRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  FavoritosRoute: typeof FavoritosRoute
  MeusPedidosRoute: typeof MeusPedidosRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  PedidoSucessoIdRoute: typeof PedidoSucessoIdRoute
  PedidoIdRoute: typeof PedidoIdRoute
  RSlugRoute: typeof RSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-pedidos': {
      id: '/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/meus-pedidos'
      preLoaderRoute: typeof MeusPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficios': {
      id: '/beneficios'
      path: '/beneficios'
      fullPath: '/beneficios'
      preLoaderRoute: typeof BeneficiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido-sucesso/$id': {
      id: '/pedido-sucesso/$id'
      path: '/pedido-sucesso/$id'
      fullPath: '/pedido-sucesso/$id'
      preLoaderRoute: typeof PedidoSucessoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/units': {
      id: '/_authenticated/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AuthenticatedUnitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promotions': {
      id: '/_authenticated/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AuthenticatedPromotionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loyalty': {
      id: '/_authenticated/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof AuthenticatedLoyaltyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance-ai': {
      id: '/_authenticated/finance-ai'
      path: '/finance-ai'
      fullPath: '/finance-ai'
      preLoaderRoute: typeof AuthenticatedFinanceAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultor': {
      id: '/_authenticated/consultor'
      path: '/consultor'
      fullPath: '/consultor'
      preLoaderRoute: typeof AuthenticatedConsultorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/builders': {
      id: '/_authenticated/builders'
      path: '/builders'
      fullPath: '/builders'
      preLoaderRoute: typeof AuthenticatedBuildersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/r/$slug/': {
      id: '/r/$slug/'
      path: '/'
      fullPath: '/r/$slug/'
      preLoaderRoute: typeof RSlugIndexRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/r/$slug/sobre': {
      id: '/r/$slug/sobre'
      path: '/sobre'
      fullPath: '/r/$slug/sobre'
      preLoaderRoute: typeof RSlugSobreRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/r/$slug/montar': {
      id: '/r/$slug/montar'
      path: '/montar'
      fullPath: '/r/$slug/montar'
      preLoaderRoute: typeof RSlugMontarRouteImport
      parentRoute: typeof RSlugRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedBuildersRoute: typeof AuthenticatedBuildersRoute
  AuthenticatedConsultorRoute: typeof AuthenticatedConsultorRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedFinanceAiRoute: typeof AuthenticatedFinanceAiRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedLoyaltyRoute: typeof AuthenticatedLoyaltyRoute
  AuthenticatedMenuRoute: typeof AuthenticatedMenuRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPromotionsRoute: typeof AuthenticatedPromotionsRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedUnitsRoute: typeof AuthenticatedUnitsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedBuildersRoute: AuthenticatedBuildersRoute,
  AuthenticatedConsultorRoute: AuthenticatedConsultorRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedFinanceAiRoute: AuthenticatedFinanceAiRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedLoyaltyRoute: AuthenticatedLoyaltyRoute,
  AuthenticatedMenuRoute: AuthenticatedMenuRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPromotionsRoute: AuthenticatedPromotionsRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedUnitsRoute: AuthenticatedUnitsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface RSlugRouteChildren {
  RSlugMontarRoute: typeof RSlugMontarRoute
  RSlugSobreRoute: typeof RSlugSobreRoute
  RSlugIndexRoute: typeof RSlugIndexRoute
}

const RSlugRouteChildren: RSlugRouteChildren = {
  RSlugMontarRoute: RSlugMontarRoute,
  RSlugSobreRoute: RSlugSobreRoute,
  RSlugIndexRoute: RSlugIndexRoute,
}

const RSlugRouteWithChildren = RSlugRoute._addFileChildren(RSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BeneficiosRoute: BeneficiosRoute,
  ClienteRoute: ClienteRoute,
  EntrarRoute: EntrarRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  FavoritosRoute: FavoritosRoute,
  MeusPedidosRoute: MeusPedidosRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  PedidoSucessoIdRoute: PedidoSucessoIdRoute,
  PedidoIdRoute: PedidoIdRoute,
  RSlugRoute: RSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
